export const site = {
  name: "Udaan Labs",
  tagline: "Software engineered for takeoff.",
  description:
    "Udaan Labs is an independent digital engineering studio based in India. We architect and ship high-reliability mobile apps, real-time web products, and production MVPs without agency bloat.",
  images: {
    aboutHero: "/projects/about-hero.jpg",
    team: "/projects/team.jpg",
  },
  nav: [
    { label: "Gate Info", href: "#about" },
    { label: "Departures", href: "#projects" },
    { label: "Fleet", href: "#services" },
    { label: "Flight Plan", href: "#process" },
    { label: "Control Tower", href: "#contact" },
  ],
  hero: {
    gateCode: "GATE DEL-01",
    flightNumber: "UL-2026",
    status: "ON TIME",
    eyebrow: "New Delhi · Bangalore · Remote Worldwide",
    title: "We build the software. We clear it for takeoff. We hand you the controls.",
    subtitle:
      "A dedicated engineering crew of senior developers and product designers. We don't bill you for 40-page strategy decks or account managers — on day two we establish a shared Git repository, push working test builds to your phone every Thursday at 16:00 IST, and get your software live in 3 to 6 weeks.",
    primaryCta: { label: "View Departures", href: "#projects" },
    secondaryCta: { label: "Contact Tower", href: "#contact" },
  },
  services: [
    {
      code: "AC-01",
      title: "Mobile Aircraft (iOS & Android)",
      role: "Cross-Platform & Native Flight Decks",
      body: "Flutter and React Native applications engineered for zero-reception environments with sub-100ms offline transaction logging. We test on physical test devices over degraded 3G throttles before TestFlight submission because silky animations on an M3 MacBook frequently stall on mid-range hardware in the field.",
      image: "/projects/liftfit.jpg",
      specs: ["Offline SQLite Sync", "Sub-100ms Input", "Biometric / Hardware API"],
    },
    {
      code: "AC-02",
      title: "High-Speed Web Transports",
      role: "Next.js Platforms & Commerce Engines",
      body: "Headless web apps and custom platforms scoring 98+ across all Core Web Vitals. We optimize server-side cache invalidation, trim JS bundle payloads down to essentials, and ensure zero layout shift during high-concurrency traffic surges.",
      image: "/projects/northline.jpg",
      specs: ["99 Lighthouse Score", "Edge CDN Routing", "Shopify Storefront API"],
    },
    {
      code: "AC-03",
      title: "First Production MVPs",
      role: "Rapid 3–5 Week Launch Sprints",
      body: "A battle-tested initial release deployed to live staging in under a month. We help founders cut speculative 'phase 2' feature creep to get real URLs in front of customers, finding out what actually breaks under daily operational volume.",
      image: "/projects/harbor.jpg",
      specs: ["Fixed Scope Lock", "Weekly TestFlight", "30-Day Launch Warranty"],
    },
  ],
  facts: [
    { label: "Crew Composition", value: "2–4 Senior Engineers" },
    { label: "Current Runway", value: "Available For New Work" },
    { label: "Departure Base", value: "India · GMT+5:30" },
    { label: "Release Cadence", value: "Weekly Thursday Builds" },
  ],
  whyUs:
    "When you partner with Udaan Labs, you communicate directly with the engineer writing the database queries and the designer styling the SVG components. Last November, when an operations client encountered a sudden barcode compliance format change 48 hours before Black Friday, we jumped on a live screen-share at 23:00 and deployed a verified hotfix in 40 minutes instead of filing a support ticket.",
  process: [
    {
      step: "01",
      flightCode: "PRE-FLIGHT",
      title: "Flight Plan & Scope Lock",
      body: "A 45-minute technical session to define database schema, 3rd-party API dependencies, and the exact boundary of what gets built for V1. You receive a single-page agreement with fixed deliverables, price, and milestone dates.",
    },
    {
      step: "02",
      flightCode: "TAXIWAY",
      title: "Interactive Flow Prototypes",
      body: "Before writing the persistence layer, we construct interactive prototypes. You tap through real navigation mechanics and typography on your phone, resolving UI edge cases when adjustments are still rapid and inexpensive.",
    },
    {
      step: "03",
      flightCode: "CRUISE",
      title: "Thursday Build Cycles",
      body: "We push updates to a live staging domain and TestFlight every Thursday afternoon. You get a changelog of closed issues and a screen recording of new features so progress is concrete, verifiable, and on schedule.",
    },
    {
      step: "04",
      flightCode: "TOUCHDOWN",
      title: "Production Handoff & Warranty",
      body: "Full deployment to your AWS, Vercel, and Apple/Google Developer accounts, accompanied by clean architecture docs and a 30-day post-launch warranty where we fix unexpected bugs at zero charge.",
    },
  ],
  projects: [
    {
      id: "FLIGHT_001",
      title: "LiftFit",
      type: "Mobile App (iOS/Android)",
      flightStatus: "DEPARTED",
      gate: "GATE 03",
      destination: "Global App Store",
      stack: "Flutter / Node.js / PostgreSQL / SQLite",
      blurb:
        "Engineered for athletes in basement gyms with zero cellular reception. Stores full training volume locally with instant sub-100ms logging, batching encrypted sync payloads until WiFi reconnects without dropping a single set.",
      tags: ["iOS", "Android", "Offline First", "SQLite Sync"],
      image: "/projects/liftfit.jpg",
      metrics: "Sub-100ms log entry · Zero cloud lock-in · 4.9★ rating",
      link: "#",
    },
    {
      id: "FLIGHT_002",
      title: "Northline",
      type: "Headless E-Commerce",
      flightStatus: "DEPARTED",
      gate: "GATE 07",
      destination: "Production Web",
      stack: "Next.js / Tailwind / Shopify Storefront API",
      blurb:
        "Replaced a 14-plugin legacy Shopify theme with a headless Next.js storefront. Reduced total asset payload by 78%, eliminating layout shifts on high-res product galleries and lowering mobile checkout funnel abandonment by 22%.",
      tags: ["Next.js", "Commerce", "Headless", "Design System"],
      image: "/projects/northline.jpg",
      metrics: "99 Lighthouse Score · 1.4s First Paint · 78% lighter bundle",
      link: "#",
    },
    {
      id: "FLIGHT_003",
      title: "Harbor Desk",
      type: "Air Logistics Cockpit",
      flightStatus: "DEPARTED",
      gate: "GATE 12",
      destination: "Warehouse Dispatch",
      stack: "React / Node.js / Realtime Redis / WebSockets",
      blurb:
        "Warehouse floor dispatch cockpit for a 3PL freight hub. Custom hardware barcode scanner integration and real-time state machine showing parcel staging queues, handling 12,000+ daily scans across 8 dock doors without page refresh.",
      tags: ["Dashboard", "Logistics", "WebSockets", "Hardware Scanner"],
      image: "/projects/harbor.jpg",
      metrics: "12,000 daily parcel dispatches · 0 memory leaks in 16hr shifts",
      link: "#",
    },
  ],
  contact: {
    heading: "Request Clearance / Start a Project",
    body: "Transmit your project brief, target launch date, and existing requirements. We review every transmission directly and respond within 24 hours with technical feasibility, team availability, and ballpark pricing.",
    email: "hello@udaanlabs.com",
    phone: "",
    callsign: "UDAAN TOWER // 124.850 MHz",
    location: "India · GMT+5:30 (Daily overlap with UK, EU & US East)",
  },
} as const;
